### ISSUE TITLE
RuntimeError: The size of tensor a (31) must match the size of tensor b (32) at non-singleton dimension 3

### ISSUE THREAD

**Issue by isshenye** [xy-guo/MVSNet_pytorch#24]
`Traceback (most recent call last):
  File "eval.py", line 307, in <module>
    save_depth()

  File "eval.py", line 118, in save_depth
    outputs = model(sample_cuda["imgs"], sample_cuda["proj_matrices"], sample_cuda["depth_values"])

  File "/home/amax/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/amax/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)

  File "/home/amax/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])

  File "/home/amax/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output

  File "/home/amax/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)

  File "/home/amax/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/amax/shenye/colmapTest1/MVSNet_pytorch-master/models/mvsnet.py", line 132, in forward
    cost_reg = self.cost_regularization(volume_variance)

  File "/home/amax/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/amax/shenye/colmapTest1/MVSNet_pytorch-master/models/mvsnet.py", line 66, in forward
    x = conv4 + self.conv7(x)

### RuntimeError: The size of tensor a (31) must match the size of tensor b (32) at non-singleton dimension 3`

Hello,how do you deal this problem?

**Comment by hanamizukigakki** [comment]
we met the same problem, is it solved now ？

**Comment by isshenye** [comment]
没，难顶，可能是我自己拍的图片太大了，我用数据集里的图片就可以跑，后来用VisMVSNet跑成功了

**Comment by isshenye** [comment]
> we met the same problem, is it solved now ？

没，难顶，可能是我自己拍的图片太大了，我用数据集里的图片就可以跑，自己拍的图片后来用VisMVSNet跑成功了

**Comment by MiZhenxing** [comment]
The height and width of the original image should be divisible by 32 because the depth map is 1/4 size and the 3D cost network performs "stride=2" three times.
