### ISSUE TITLE
跑测试集出现的维度问题

### ISSUE THREAD

**Issue by 4orange** [xy-guo/MVSNet_pytorch#30]
(120, 160)
(128, 160, 3)
Traceback (most recent call last):
  File "/home/stu5/dl_mvs/MVSNet_注释代码/eval.py", line 347, in <module>
    filter_depth(scan_folder, out_folder, os.path.join(args.outdir, 'mvsnet{:0>3}_l3.ply'.format(scan_id)))
  File "/home/stu5/dl_mvs/MVSNet_注释代码/eval.py", line 295, in filter_depth
    color = ref_img[1:-2:4, 1::4, :][valid_points]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 128 but corresponding boolean dimension is 120

**Comment by zhao-you-fei** [comment]
请问这个问题您解决了吗?可以分享下怎么解决的吗?

**Comment by qwerwsc1** [comment]
解决了 我自己代码出现问题 可以自己debug看看自己的代码，具体我也忘了
